spring.application.name=payment-service

# HTTP
server.port=8085

# Datasource (payment_db created by infra/postgres/init)
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=ecommerce
spring.datasource.password=ecommerce
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

